### ISSUE TITLE
Have player show podcast title

### ISSUE THREAD

**Issue by fterbo** [davinkevin/Podcast-Server#101]
The overlay player on the bottom of the web page shows the artwork for the podcast, but not the episode name, which would be really useful.

**Comment by davinkevin** [comment]
You talk about the original web-ui or the new one ? 

I think I have a task about this on the v2 (which can be accessed by the `/v2` in the url). But like in many tickets, I'll be glad to review PR 👍

**Comment by fterbo** [comment]
/v2 doesn't even seem to allow me access to all of the episodes for podcasts, as there's no pagination?

**Comment by davinkevin** [comment]
The `/v2` is under heavy construction, so it's really not production ready, but I'm working on it.
