### ISSUE TITLE
Broken build

### ISSUE THREAD

**Issue by baczus** [davinkevin/Podcast-Server#103]
There is some problem with versions in pom files, because after execution command _mvn clean install_ I receive following error:

> [ERROR] Failed to execute goal on project Backend: Could not resolve dependencies for project lan.dk.PodcastServer:Backend:jar:2018.5.0: The following artifacts could not be resolved: lan.dk.PodcastServer:frontend-angularjs:jar:1.0.0, lan.dk.PodcastServer:frontend-angular:jar:1.0.0: Failure to find lan.dk.PodcastServer:frontend-angularjs:jar:1.0.0 in https://jitpack.io was cached in the local repository, resolution will not be reattempted until the update interval of jitpack.io has elapsed or updates are forced -> [Help 1]

**Comment by davinkevin** [comment]
Do you try to build against master or dev?

**Comment by davinkevin** [comment]
BTW, Master and Dev are green on travis => 

![image](https://user-images.githubusercontent.com/1970922/40697984-1c46867e-63cd-11e8-847d-e5c9e2c5cfc7.png)

**Comment by baczus** [comment]
I try build against master.
Problem occurs, because there is a problem with versions in pom files.
Maven builds _fronted-angular_ jar in version _2018.5.0_ (according to pom.xml)
But dependency to  _fronted-angular_ in  _backend_ module is set to version 1.0.0, which maven can't resolve:

>   <dependency>
            <groupId>lan.dk.PodcastServer</groupId>
            <artifactId>frontend-angularjs</artifactId>
            <version>1.0.0</version>
        </dependency>

If you want to reproduce the issue, you have to build project on clean local Maven repository.

**Comment by davinkevin** [comment]
I think it was fixed in recent commit. Try to do this on dev branch please

**Comment by baczus** [comment]
You're right on dev branch problem is fixed.
