### ISSUE TITLE
RSS feed only contains the last 50 episodes

### ISSUE THREAD

**Issue by nbastin** [davinkevin/Podcast-Server#104]
If you have a feed on the server with more than 50 episodes, the rss feed generated by the server itself to be given to local clients will only have the most recent 50 episodes in it, and there does not appear to be a 
way for clients to get episodes past the first 50.

**Comment by davinkevin** [comment]
Yes, there is a way, but like the whole project, this is not documented 😊

You can add the parameter `limit` to `false` in the query string to prevent this : 
> https://github.com/davinkevin/Podcast-Server/blob/dev/backend/src/main/java/lan/dk/podcastserver/controller/api/PodcastController.java#L86

In this case, you will have the url with this format : 
```
https://my.wonderful.domain/api/podcasts/1f65b3a3-aaba-4252-a709-073599e3ef52/rss?limit=false
```

This parameter was here to prevent download a RSS which can contains thousands of item.

If it's ok for you, can you please close the issue?

**Comment by nbastin** [comment]
Thanks, that works.

**Comment by davinkevin** [comment]
Thank you for using Podcast-Server 👍

Let me know if you have some others problem
