### ISSUE TITLE
Docker install please

### ISSUE THREAD

**Issue by gerroon** [davinkevin/Podcast-Server#112]
Hi

This looks interesting and I definetely would like to try it but "npm" thatttt thing never works on my system properly, I just tried to install this and again

I am not a java or js dev and I hate npm for all the issues and time wastes it gives me. 

Would not it be much easier to provide a Docker install for idiots like me, the nice benefits of providing a Docker or Snap package is that you wont get people like me flooding your bug reports.

thanks

```
[ERROR] npm ERR! 
[ERROR] npm ERR! Failed at the podcast-server@2019.1.0 prebuild script 'npm install'.
[ERROR] npm ERR! This is most likely a problem with the podcast-server package,
[ERROR] npm ERR! not with npm itself.
[ERROR] npm ERR! Tell the author that this fails on your system:
[ERROR] npm ERR!     npm install
[ERROR] npm ERR! You can get information on how to open an issue for this project with:
[ERROR] npm ERR!     npm bugs podcast-server
[ERROR] npm ERR! Or if that isn't available, you can get their info via:
[ERROR] npm ERR! 
[ERROR] npm ERR!     npm owner ls podcast-server
[ERROR] npm ERR! There is likely additional logging output above.
[ERROR] 
[ERROR] npm ERR! Please include the following file with any support request:
[ERROR] npm ERR!     /opt/Podcast-Server/frontend-angularjs/npm-debug.log
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for podcastserver 2019.1.0:
[INFO] 
[INFO] frontend-angularjs ................................. FAILURE [02:38 min]
[INFO] frontend-angular ................................... SKIPPED
[INFO] backend ............................................ SKIPPED
[INFO] podcastserver ...................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:41 min
[INFO] Finished at: 2019-01-28T11:08:13-06:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.29:npm (npm install) on project frontend-angularjs: Failed to run task: 'npm run build' failed. (error code 1) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

**Comment by davinkevin** [comment]
I share your feelings about NPM... 
Right now, the v1 (angularjs) version of the frontend requires a GitHub token to be built, sadly... and I don't think I will change it because I'm trying (to find the time) to totally rework on this part to use Angular (v6+).

But, for people like you, you have access in the readme to two other solutions: 
* Fat-Jar 
* Docker images

> The application is available in fat-jar format or in docker images

Let me know if this is ok for you 😉

**Comment by gerroon** [comment]
I blew it!

What kind of idiot would search for Docker images in the "issues", then files a bug report when he can't find any entry in the issues section"? That is me.

That aside, Docker works. I like it. 

How can I create a Docker volume for the subscriptions and the downloads?

thanks

**Comment by davinkevin** [comment]
You just have to override the `podcastserver.rootfolder` from the environment (with `PODCASTSERVER_ROOTFOLDER`) and mount a volume for it.

For example:
```bash
$ docker run ... -e PODCASTSERVER_ROOTFOLDER=/opt/ps/ -v /host/path:/opt/ps ...
```

You have to do the same thing for the database by changing the `SPRING_DATASOURCE_URL` with a value to indicate where to store the database file (like `jdbc:h2:/opt/ps/db` in order to store it in the same volume define previously)

**Comment by gerroon** [comment]
Ok sounds good except that I know donkey poop about `jdbc:h2` What am I supposed to do with that? It is not a path, what is it?

**Comment by Piggeldi2013** [comment]
Just leave the jdbc:h2 in front of that path, e.g. use jdbc:h2:/opt/ps/db

Set that with the -e SPRING_DATASOURCE_URL=jdbc:h2:/opt/ps/db

Just be aware that you set the path that is supposed to be in your docker container, not the external folder. 
The -v option mentioned by @davinkevin will do the rest.
