### ISSUE TITLE
feat(deploy): provide a docker compose solution

### ISSUE THREAD

**Issue by davinkevin** [davinkevin/Podcast-Server#114]
We should provide a docker compose with:
* Podcast-Server image for business logic
* H2 database for data persistence
* NGINX to serve file stored on disk (images, audio, video)
* Traefik for reverse proxy ?

@neonox31 did you see? I plan to use traefik 😱(or not...)

**Comment by gerroon** [comment]
I blew it!

What kind of idiot would search for Docker images in the "issues", then files a bug report when he can't find any entry in the issues section"? That is me.

That aside, Docker works. I like it. 

How can I create a Docker volume for the subscriptions and the downloads?

thanks

**Comment by robflate** [comment]
Interested in a docker compose setup too. Did this happen or does anyone have a working example? Thanks.

**Comment by davinkevin** [comment]
This is still open, so not yet implemented. 

This isn't in my top priority list, but I could do a review on a PR if someone is interested in doing this.

**Comment by davinkevin** [comment]
I've made a Kubernetes solution instead of docker compose. You can play with it if you want with docker for mac or K3S.

**Comment by eyadsibai** [comment]
I understand that an existing Kubernetes solution exist, but I would say a docker compose is much more friendly for local machine use. I am really interested in using your project, would be nice to be able to integrate it with https://dockstarter.com/
