### ISSUE TITLE
Opml import

### ISSUE THREAD

**Issue by gerroon** [davinkevin/Podcast-Server#115]
Hi

Is it possible to import and existing .opml file to bring in my own previous podcast subcriptions? If not can this be a feature request please?

thanks

**Comment by davinkevin** [comment]
This can be a feature, but I really don't know when this will implemented. 

I'm currently splitting the podacst-server to improve its scalability and simplify improvement... and this is taking a lot of time, and due to my current job, I already don't have enough time 😅

**Comment by gerroon** [comment]
Sure, that is totally understandable.
