### ISSUE TITLE
App yml and volume for fat jar docker?

### ISSUE THREAD

**Issue by gerroon** [davinkevin/Podcast-Server#120]
Hi

Can you please add a documentation for where to find the application.yml and also how to add a custom volume for the downloads location?

docker run -it -v /path/to/application.yml:/opt/podcast-server/application.yml -p 8080:8080 davinkevin/podcast-server:dev

**Comment by davinkevin** [comment]
This is a good idea to provide documentation to start the project. 

I would like this documentation to be located with the code, so people (like you) can provide through pull request some enhancement to the code or the documentation.

What do you think, can you provide documentation for the case you ask?

**Comment by pierow2k** [comment]
On the [GitHub page under `Installation`](https://davinkevin.github.io/Podcast-Server/#installation) there is a reference to the following:

> If you want to tweak the application, you have to create an application.properties (or yml) (based upon application-example.yml template) …

The link to `application-example.yml` points to the non-existent URL:
[https://github.com/davinkevin/Podcast-Server/blob/master/src/main/resources/application.yml](https://github.com/davinkevin/Podcast-Server/blob/master/src/main/resources/application.yml)

and looking through the repository, I am unable to find a file called `application.yml`

@gerroon, when you said

> Can you please add a documentation for where to find the application.yml…

Is this what you were referring to?

**Comment by gerroon** [comment]
Yes. We need the files and the locations.

**Comment by davinkevin** [comment]
The link to the file is here https://gitlab.com/davinkevin/Podcast-Server/blob/635237ed9a2c34852407cd83ba7610959c9898c6/backend/src/main/resources/application.yml (project moved to gitlab, github is just a mirror).

I'm doing some modification to the docker image, so in a near future, the `application.yaml` should be put at the `/` of the container.

**Comment by gerroon** [comment]
Can you also tell us how to properly add a custom volume for downloads and database etc for the Docker stuff so that this is permanent. The DOcker hub page does not mention anything and I cant tell by looking at the application.yml, if those are internal or external locations.

**Comment by davinkevin** [comment]
You have to use parameters of the `docker` command line to "mount" a volume from the host into the guest container (with the `-v` parameter). With this, you can share a filesysteme across a reboot of the container. 

For the application, you can use the `-e` parameter to define some environment variables into the docker container. All the `spring` way of configure the app is available to you: 
> https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html#boot-features-external-config

Currently, I deploy my application in K8S, I configure it by mounting a file in the root file system pf the container, with the name `application.yaml` and my required configuration
> https://gitlab.com/davinkevin/Podcast-Server/tree/master/backend/src/main/k8s

**Comment by raiemaille** [comment]
Hi

I think that gerron wants to know the structure of the files and directories in Docker image. I found [this link](https://github.com/davinkevin/Podcast-Server/blob/master/backend/src/main/docker/main/Dockerfile).
I gave up with application.yml and tried `-v` parameter to mount `backup`, `lucene` and `db` outside Docker. The directories are created at launch but remain empty.
What am I missing ?

Thanks for this tool.

**Comment by davinkevin** [comment]
For a few weeks, the database, Lucene, and backup are not anymore handled at the application level. They are external tasks triggered to do the job out of the application. (FYI, Lucene has been totally removed for the evolution process, we only rely on regex at SQL level for now). 

This choice was made to simplify the application and remove specific code from the main application. The final goal is to be able to move to another database (PostgreSQL) and a new indexer system (ElasticSearch) if possible, but this is not for now 😅.

To understand the way storage is handled, you can look at YAML files used to deploy the app in Kubernetes in dev env (with docker for mac) or in production with K3S.

Let me know if you need more information. 

> https://github.com/davinkevin/Podcast-Server/tree/master/backend/src/main/k8s/docker-for-mac

You have access to all the configuration I use to deploy the app in both envs, so you should be able to launch the app on your side too with this (the `./dev.sh` file and `skaffold.yaml` configuration can help too).

**Comment by gerroon** [comment]
All we need is a simple Docker setup, I am not even sure how to even start with Kubernetes.

What we need is a simple line that starts the Docker that demonstrates the custom volumes really, so that we cna download them to proper placves and feed our own custom configs and url feeds.

**Comment by gerroon** [comment]
@raiemaille 

Thank you that is exactly what I have been asking for since I opened this entry.

**Comment by davinkevin** [comment]
Be careful, you are using a very old image not maintained any more.

New images are here: https://hub.docker.com/search?q=podcastserver&type=image

It now relies on `youtube-dl` internally to be able to download more source and to have a full community supporting it 🤩
