### ISSUE TITLE
Install steps @ https://davinkevin.github.io/Podcast-Server/ do not work

### ISSUE THREAD

**Issue by karezza** [davinkevin/Podcast-Server#146]
I've followed through to the github page and see there are instructions to setup within a kubernetes cluster.

If possible, I'd like a simpler install via steps such as those at the website in the subject, or via the use of a docker-compose file.

Error received if following install at the above website:
- clean install of centos8
- installed git, maven & npm

`
[ERROR]
[ERROR] npm ERR! Linux 4.18.0-193.el8.x86_64
[ERROR] npm ERR! argv "/home/karezza/Podcast-Server/frontend-angularjs/target/node/node" "/home/karezza/Podcast-Server/frontend-angularjs/target/node/node_modules/npm/bin/npm-cli.js" "run" "build"
[ERROR] npm ERR! node v6.2.0
[ERROR] npm ERR! npm  v2.15.6
[ERROR] npm ERR! code ELIFECYCLE
[ERROR] npm ERR! podcast-server@2019.1.0 build: `gulp build`
[ERROR] npm ERR! Exit status 1
`

**Comment by maxiin** [comment]
tried using the releases jar? worked for me
I don't know how kubernetes work tho

**Comment by davinkevin** [comment]
Indeed, this documentation/site is totally out of date… I totally miss this part. 

Currently, the only installation way supported (by supported, I mean, I support… if some other want to contribute, you're welcomed) is by using kubernetes. Installation with k3s can be done in few command lines like described here: https://gitlab.com/davinkevin/Podcast-Server/-/blob/master/documentation/modules/ROOT/pages/installation/kubernetes.adoc

BTW, this issue tracker should be read only, for issue, I've switched to GitLab: http://bit.ly/podcast-server, some already ask for something similar in the past, this is why I provide this documentation (https://gitlab.com/davinkevin/Podcast-Server/-/issues/48).
