### ISSUE TITLE
Angular-Material Design

### ISSUE THREAD

**Issue by davinkevin** [davinkevin/Podcast-Server#15]
Testing of the Material design with https://material.angularjs.org/ to improve the UI and the UX
That will be an investigation and it could lead to nothing (BootStrap 3 is not so bad after all...)

**Comment by RossMBoswell330** [comment]
I think this is a good idea and promote this idea

**Comment by davinkevin** [comment]
I will wait for angular v2 to directly work with polymer

**Comment by davinkevin** [comment]
Or not... the improvement in Angular Material design is huge since the opening of this ticket.

https://material.angularjs.org/latest/#/

**Comment by davinkevin** [comment]
After a try on https://github.com/angular/material I think it's too soon for me to migrate from bootstrap to AM
