### ISSUE TITLE
feat(clipboard): add copy to play url

### ISSUE THREAD

**Issue by davinkevin** [davinkevin/Podcast-Server#37]
https://github.com/zenorocha/clipboard.js

**Comment by zenorocha** [comment]
+1 ;)

**Comment by davinkevin** [comment]
@zenorocha : Implemented, do you have a opinion on the angular integration with clipboard.js ? (cf commit in this ticket).

**Comment by zenorocha** [comment]
You might wanna check: https://github.com/sachinchoolur/ngclipboard

**Comment by davinkevin** [comment]
Thanks for the link.

But this directive have many problems : 
* Use text selector instead simply using the element (like I do in ```static link``` in Copy.js)
* doesn't destroy the element when the scope is destroyed (potential memory leak)

I will probably do some PR on it to improve it, but, for now, I keep my implementation.
