### ISSUE TITLE
DLNA support

### ISSUE THREAD

**Issue by gabriellluz** [davinkevin/Podcast-Server#78]
Hi there. I love your app.

Anyway I'm suggesting that you would create a DLNA server for Podcast-server so that we could use it with Kodi, Plex, smart TVs and so on.

**Comment by davinkevin** [comment]
Glad to hear you like the app 😉 

It's not currently planned and I don't know a lot about DLNA system and what I should add to support this, but I will look for it and let you know. 

BTW, I already use the Podcast-Server app with Google Chromecast, Google Home and Kodi (thanks to Yatse on android). You only need to have the application on the same network to share the file on those players.

Thanks

**Comment by gabriellluz** [comment]
It works with Kodi like casting, right? I mean a server. Maybe you could use code of ReadyMedia (formerly known as MiniDLNA). [Link](https://sourceforge.net/projects/minidlna/)

**Comment by gabriellluz** [comment]
Also, thanks for your hard work. :)

**Comment by davinkevin** [comment]
Yatse has an option "Send to my Media center", so I can share the direct link of the item directly to Kodi... and it starts streaming it directly from the Podcast-Server app... no need to keep the telephone or tablet on during the broadcast. 

Same thing for Google Chromecast & Google Home, a simple configuration on my network allow me to share a link from BeyondPod (or any other podcast App supporting ChromeCast) to a Chromecast  accessories.

**Comment by davinkevin** [comment]
I didn't find any implementation which should be "embedded" in the Java application. So I let you try with the previous solution mentioned in my last comment. 

Thanks for your feedback
