### ISSUE TITLE
master does not build

### ISSUE THREAD

**Issue by eduyayo** [davinkevin/Podcast-Server#90]
hi, master does not build out of the box and the release 1.0 code fails also on missing class com/mysema/query/annotations/QueryEntities

**Comment by davinkevin** [comment]
It's now fixed on master
https://travis-ci.org/davinkevin/Podcast-Server/branches

The class QueryEntities is generally generated during the build process of maven.

**Comment by davinkevin** [comment]
This is a problem with your maven / JDK setup.

**Comment by nicolas-zozol** [comment]
Canno t build neither

```xml
<dependency>
           <groupId>lan.dk.PodcastServer</groupId>
           <artifactId>frontend-angularjs</artifactId>
           <version>1.0.0</version>
       </dependency>
```
