### ISSUE TITLE
Cover-art is not being displayed

### ISSUE THREAD

**Issue by nholben** [davinkevin/Podcast-Server#92]
Cover-art files are being downloaded and are present in "/opt/podcast-server/podcasts/mypodcast/cover.jpg"

Am running through your docker image (https://hub.docker.com/r/davinkevin/podcast-server/) and have mounted "/opt/podcast-server/podcasts" to a local directory. I've tried without the volume mount and still have the same issue.

Screenshot of issue below, it also happens for individual episodes. I can send logs too if you need.

Thanks!

![screen shot 2018-03-05 at 11 13 47 am](https://user-images.githubusercontent.com/19359193/36985849-5d8589f0-2066-11e8-86fc-fe95d0be4937.png)

**Comment by davinkevin** [comment]
Thanks for the report.

I will try to find the origin of the problem this weekend

**Comment by davinkevin** [comment]
Which version did you use on docker?

**Comment by davinkevin** [comment]
I found a silent error on travis about the deployment of the docker image. I will have to check that 
> https://travis-ci.org/davinkevin/Podcast-Server/builds/349134295#L4853

Due to this, the latest / dev image are not deployed any more since 3 month 😢

**Comment by davinkevin** [comment]
For information, from Docker hub, you now have two version released : 
* `latest` which is based upon `master` branch
* `dev` which is based upon `dev` branch

Could you say to me if those versions fix the bug? 

Thanks 😉

**Comment by nholben** [comment]
Perfect! Thank you so much for fixing that. The update totally solved the problem. Great work on this application, I look forward to using it!

**Comment by davinkevin** [comment]
👍
