### ISSUE TITLE
How to make Podcasts/Config persistent with docker

### ISSUE THREAD

**Issue by Gomez** [davinkevin/Podcast-Server#94]
I use the docker to get the server running. Unfortunately the Podcast/Logs/DB does not get saved in the mapped directory. Here is how i start it:

```
docker run -it \
  -v /path/podcast_server/application.yml:/opt/podcast-server/application.yml \
  -v /path/Podcasts/:/tmp/podcast-server/ -p 8070:8070 \
  --dns X.X.X.X davinkevin/podcast-server:dev
```

**Comment by davinkevin** [comment]
Sorry, I totally miss this question 😅

Currently, some of the value are defined as env variable inside the Dockerfile, so changing it inside the application.yml doesn't affect the configuration...  You can see it here : 
https://github.com/davinkevin/Podcast-Server/blob/dev/backend/src/main/docker/Dockerfile#L9

From my point of view, I have to force those value inside a docker container in case someone try to override those... but in your case, this is a problem.

If you have an idea on "how to do this simply", I'll be glad to implement / valid a PR about it
