### ISSUE TITLE
Links are embedded with "localhost" instead of real IP

### ISSUE THREAD

**Issue by fterbo** [davinkevin/Podcast-Server#96]
All of the images in my UI are broken because it embeds the FQDN in all links as being "localhost", instead of relative, or the real value:

`http://localhost:8080/api/podcast/0816c96f-a401-4f51-9863-5cf5c056e93c/cover.jpg`

Is there some way to configure this value?

**Comment by davinkevin** [comment]
How do you launch the application? Which version? (I think this is a old error...)

**Comment by fterbo** [comment]
I copied the entrypoint from your dockerfile (we can't use it because we have to use different networking, but otherwise is very similar):

```
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
```

This is the Podcast-Server.jar from the current releases page.

**Comment by fterbo** [comment]
It's v1.0.0, which appears to be....really old.  But that's the latest fat-jar that exists?

**Comment by davinkevin** [comment]
yes, I haven't published any version since then... because no one ask for it and I daily publish the docker images (based on dev and master), so the fat jar seems to be a too complex alternative from my point of view (required ffmpeg, rtmpdump & other tools).

Can I close this issue ?

**Comment by fterbo** [comment]
Sure, although perhaps you should remove the fat jar from the releases page?  Alternatively you clearly *are* building it, so maybe just post a master one when you build?

**Comment by fterbo** [comment]
The URL is still wrong in master that I built just now:

`http://localhost:8080/api/podcast/6ddc6a4b-946d-40b2-97ee-0555183c84ff/cover.jpg`

**Comment by davinkevin** [comment]
I build it everyday, so I think Github will throw an alert if I store 60mb everyday in the release part.

I was thinking about releasing master each month, with a version name like 2018.05.0

**Comment by fterbo** [comment]
https://www.dropbox.com/s/020egezpvu9jqjm/Screenshot%202018-05-01%2010.39.10.png?dl=0

This is better than before, but not great.. :-/

**Comment by fterbo** [comment]
Unfortunately the problem seems to be just with old podcasts, and not new ones.  Is there any way for me to fix the old ones?  If I edit the cover URL value it completely wipes it out.

**Comment by fterbo** [comment]
I fixed it - the endpoint changed from `/api/podcast` to `/api/podcasts`, and no longer contains the FQDN component.

**Comment by davinkevin** [comment]
Well done 👍
