### ISSUE TITLE
Server takes incredible amount of ram

### ISSUE THREAD

**Issue by fterbo** [davinkevin/Podcast-Server#97]
```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                   
 3019 root      20   0 9880.9m 1.510g  14136 S   0.3  9.6   3:11.58 java                                                                                      
```

Is there some way to reduce the amount of required memory?  This is with one podcast playing on one remote host.

**Comment by davinkevin** [comment]
The Lucene index are stored on ram... so this could lead to this.

I am currently working on migration to Java 10 which will reduce ram consumption and after that, I will try to investigate on why so much ram are used. BTW, I've add glowroot (APM) to help me follow CPU/mem and others consumption...

If you want to help on this subject, you are welcome !

**Comment by fterbo** [comment]
I am sadly not much of a java developer, but I am happy to help out with any kind of data collection and such.

**Comment by davinkevin** [comment]
Don't forget this application holds everything... including the database, so it's from my point of view legit to consume more ram than any other application.

**Comment by davinkevin** [comment]
The application has been split, so the resident memory is around 1Gb currently without limitation in my K8S cluster. 

But, you can define a limit for ram consumption through java parameters (-Xmx and others) to force the JVM to consume less memory. If you have memory, java will use it to improve the application, if you reduce it, the application could be slower.
